### ISSUE TITLE
Comments are not kept after write_to_file

### ISSUE THREAD

**Issue by lrascao** [QEDK/ini-rs#1]
```
[a_section]
a=1
#b=1
```
after `write_to_file` is called we end up with:
```
[a_section]
a=1
```

**Comment by lrascao** [comment]
sorry, wrong project

**Comment by QEDK** [comment]
@lrascao if it's possible, could you tell me what features the other crate has you'd like to see in this crate as well 😄 I'd be grateful for any feedback.

**Comment by lrascao** [comment]
sure, main one that seems to be missing here (at least not advertised in README.md) is the ability to write an .ini file
